### ISSUE TITLE
Apvienot daudzvārdniekus, kas atšķiras tikai ar gramatiku

### ISSUE THREAD

**Issue by lauma** [LUMII-AILab/LVWordNet#17]
Importa laikā ir palikuši neapvienoti MWE, kam atšķīrās pie šķirkļa pievienotas gramatikas. Tos tagad vajag apvienot, piemēram, garmatikas pārvietojot pie nozīmēm.
Šķirkļi:
```
Acu vāki
Aizmugures žurka
Ar diegiem nav aršana
Bada dzeguze
Bērnu saņēmēja
Brīvās svārstības
Cūkas mezgls
Dot uz kartītēm
Draudzes gans
Godmaņa kurvis
Ģenealoģiskā valodu klasifikācija
Ieiet galvā
Ieiet galvā
Iepūst miglu acīs
Iesist bietē
Ievilkt nāsīs
Kā akla vista
Krusta karš
Krusta karš
Laist tautās
Laist vagu
Līst pakaļā
Lopu suns
Melnā kaste
Muļķa desa
Ne čaku, ne grabu
Neiet krastā
Nolaist dibenā
Nolaist ūdeni
Noņemt krievos
Paunu žīds
Piesist pēdu
Piesist pēdu
Pļāpu kule
Pļāpu kule
Rata cepure
Rokas puisis
Salonu lauva
Sist pa lampu
Skaņu raksts
Skatīties baltām acīm
Smērēt papīrus
Stumt māgā
Suņu dienas
Turēt dūšu
Uguns sprediķis
Velna pulveris
Vēja grābslis
Zaļa gaļa
Zelta teļš
Zelta teļš
Zelta teļš
Zemes ierīcība
```

Oriģinālais ziņojums: 
[tezaurs-mwe-not-merged-different-gram.json.txt](https://github.com/LUMII-AILab/LVWordNet/files/5101723/tezaurs-mwe-not-merged-different-gram.json.txt)

**Comment by lauma** [comment]
Un daudzvārdnieku šķirkļiem, kas tāpat tiek apskatīti, "leksēmām" vajag pārtaisīt pirmo burtu par mazo, ja tas nav īpašvārds vai frāze nav pilns teikums ar pieturzīmi galā.

**Comment by lrituma** [comment]
Apvienoti un pārbaudīti.
