### ISSUE TITLE
Tulpjkoks - dublicēta leksēma?

### ISSUE THREAD

**Issue by lauma** [LUMII-AILab/LVWordNet#18]
Importa skripti apgalvo, ka šķirklī "tulpjkoks" precīzi tāpati leksēma ir bijusi divreiz. Ja tā, vajag lieko izmest, ja nē, tad jāiereģistrē paradigmu atšķirība.

**Comment by lrituma** [comment]
Šķirklis tulpjkoks izdzēsts, šķirklī tulpjukoks tagad ir rakstības variants tulpjkoks.
