### ISSUE TITLE
Labot vārdšķiru pāris šķirkļiem

### ISSUE THREAD

**Issue by lrituma** [LUMII-AILab/LVWordNet#38]
milzu, papildu - ielikt vārdšķiru īpašības vārds.
vairāki - ielikt vārdšķiru un citas lietas
hakki un bordo dabūjušas lietvārda vārdšķiru - jāpārdomā, vai tā ir?
neto nav dabūjis neko.

**Comment by lauma** [comment]
Tagad tehniski ir iespējams ielikt vārdšķiru.

**Comment by lrituma** [comment]
Neto ieliku , ka ir īpašības vārds, jo tādas ir divas nozīmes. Bet mlvv ir sadalījis divus homonīmus neto 1 un neto 2. Savukārt bordo un haki viņi pasniedz kā nelokāmos lietvārdus, kuriem viena nozīme ir īpašības vārda nozīmē. Mums vajadzētu apdomāt un visiem trim darīt vienādi.

**Comment by lrituma** [comment]
Visu satīriju. Bruto un neto palika par nelokāmiem īpašības vārdiem, kuriem ir arī apakšnozīme ar konversiju.
Haki un bordo paliek par nelokāmiem lietvārdiem.
