### ISSUE TITLE
Tehniski gļukaini karogi šķirkļos "tāds" , "Lamija"

### ISSUE THREAD

**Issue by lauma** [LUMII-AILab/LVWordNet#41]
- Šķirklī "tāds" 4. nozīmē ierobežojumos jāizlabo karodziņš "Citi":"Salīdzinājuma konstrukcija" uz "Sintaktisks ierobežojums":"Salīdzinājuma konstrukcija".
- Šķirklī "Lamija" 2. nozīmē ierobežojumos jāizlabo karodziņš "Citi":"Ar mazo sākumburtu" uz "Lielo/mazo burtu lietojums":"Ar mazo sākumburtu".

Priekšnosacījums: ierobežojumu rediģēšana.

**Comment by lrituma** [comment]
Izlabots.
