### ISSUE TITLE
Čipsi un čipši

### ISSUE THREAD

**Issue by lauma** [LUMII-AILab/LVWordNet#47]
Apvienoju vienā šķirklī čipši un čipsi, jo nu tie ir rakstības varianti, bet nemācēju izlemt, kuru likt par šķirkļa galveno leksēmu un līdz ar to, kādam jābūt šķirkļavārdam - čipsis un čipši vai čipss un čipsi. Lūdzu, labojiet, ja vajag. Vai klapējiet šo ciet.

**Comment by lrituma** [comment]
Ieliku galveno čipsi pēc mlvv. Valodas konsultācijās un terminu komisijas protokolos neko neatrodu par šo tēmu.
