### ISSUE TITLE
Šķirkļavārdam tuvi šķirkļi, kas nav tuvi šķirkļi

### ISSUE THREAD

**Issue by VaBaiba** [LUMII-AILab/LVWordNet#60]
Mulstu un iebilstu, ka darbības vārdiem kasēt un kāsēt (sk. ) kreisajā stūrī tiek norādīts: locījums šķirklī kasete.

**Comment by lauma** [comment]
1) meklēsana locījumos notiek arī "neredzamajos", t.i., tabulās neparādītajos locījumos - vokatīvos, pārākajās pakāpēs, divdabjos utt.
2) "līdzīgi rakstīts" ir koda nosaukums tai grupa, kam atsķiras tikai diakritiskās zīmes un lielie burti.
3) tapēc sanāk, ka kāsēt ir līdzīgs automātiski izdomātajam kasetes vokatīvam "kaset!"

Tā tas ir noticis. Ja mēs gribam, lai tā nenotiek, jādomā, kuru soli mēs gribam ierobežot un kādā veidā, *un* kādu iespaidu tas atstās uz citu šķirkļu meklēšanu.

Pirmais solis man ir svarīgs tiešā veidā neizrakstītu formu atrašanai, taču varam apsvērt diskriminēt vokatīvu šajā meklēšanā. Otrais solis šķita ļoti svarīgs Spektoram un Normundam, lai samazinātu to, ka lietotājs uzraksta tizli un tāpēc neatrod tēzaurā esošu vārdu. Vēl mēs varam pārdomāt precīzāk, kādus nosacījumus mēs uzliekam pašu to ieteikumu rādīšanai - es noteikti gribu, lai, pat ja atrod šķirkli, tur malā rāda, ka meklētā/skatītā forma ir forma no kādām citām šķirkļu leksēmām, taču varam apsvērt, vai tur jālieto garumzīmju atmešana.

**Comment by lauma** [comment]
Un visbeidzot tehnisks aspekts: šī neizskatās pēc datu problēmas, bet pēc saprogrammētās saskarnes uzlabojuma, tāpēc vislabākā vieta šādai biļetei būtu https://gitlab.com/ailab/tezaurs/-/issues/ , kur iet viss programmējamais, bet tā kā tas ir nokļuvis te, pieminu zināšanai @mikusg .

**Comment by lauma** [comment]
Taisu ciet, jo šis risinās visādos veidos gitlabā.
